"use client";
import { useEffect, useRef, useState } from "react";
import { datasetPackageHash, type IVDataset } from "../lib/iv-data";
import { loadOutdoorBundle, type OutdoorSensitivityBundle } from "../lib/outdoor-sensitivity-data";
import { materialStyle } from "../lib/material-style";
import { buildIdentity } from "../lib/build-identity";
import { rowsCsv } from "../lib/tabular-export";
import { downloadFigureFile, downloadScientificGraphic } from "../lib/browser-figure-download";
import { InfoTip } from "./InfoTip";
import { outdoorFigureExclusions } from "../lib/outdoor-sensitivity";
import { ALL_RIBBONS, ribbonSelectionLabel } from "../lib/ribbon";

const thresholds=[100,200,300] as const;
const dash:Record<number,string>={100:"3 3",200:"",300:"9 3"};
const number=(value:number|null)=>value===null?"—":value.toFixed(2);
export function OutdoorSensitivity({dataset,materials,ribbonSampleIds,ribbonSelection}:{dataset:IVDataset;materials:string[];ribbonSampleIds:ReadonlySet<string>;ribbonSelection:string}) {
 const [loaded,setLoaded]=useState<OutdoorSensitivityBundle|null>(null),[loadError,setLoadError]=useState<string|null>(null);
 const [sampleId,setSampleId]=useState(""),[metric,setMetric]=useState<"pr"|"pmpp">("pr"),[window,setWindow]=useState<3|7|14>(7);
 const [mode,setMode]=useState<"retention"|"absolute">("retention"),[graphEnd,setGraphEnd]=useState<number|null>(null),[hidden,setHidden]=useState<number[]>([]);
 const [exportError,setExportError]=useState<string|null>(null);
 const svg=useRef<SVGSVGElement>(null),hash=datasetPackageHash(dataset);
 useEffect(()=>{const controller=new AbortController();loadOutdoorBundle(hash,controller.signal).then(result=>{setLoaded(result);setLoadError(null);}).catch(error=>{if(!controller.signal.aborted)setLoadError(String(error));});return()=>controller.abort();},[hash]);
 const bundle=loaded?.compatiblePackageHashes.includes(hash??"")?loaded:null;
 const samples=dataset.samples.filter(sample=>ribbonSampleIds.has(sample.sample_uid)&&materials.includes(sample.material_family)&&bundle?.analysis.summaries.some(row=>row.sampleUid===sample.sample_uid));
 const sample=samples.find(row=>row.sample_uid===sampleId)??samples[0];
 if(!bundle)return <section className="chart-card" aria-label="Sensibilité en extérieur"><h3>Sensibilité en extérieur</h3><p role="status">{loadError??"Loading raw-derived sensitivity data…"}</p></section>;
 if(!sample)return <section className="chart-card" aria-label="Sensibilité en extérieur"><h3>Sensibilité en extérieur</h3><p>No Outdoor raw measurements for the selected materials.</p></section>;
 const scenarios=bundle.analysis.summaries.filter(row=>row.sampleUid===sample.sample_uid&&row.metric===metric);
 const displayed=scenarios.filter(row=>row.window===window);
 const allDaily=bundle.analysis.daily.filter(row=>row.sampleUid===sample.sample_uid);
 const end=graphEnd??Math.max(0,...allDaily.map(row=>row.time));
 const values=displayed.filter(row=>!hidden.includes(row.threshold)).flatMap(row=>row.daily.filter(day=>day.time<=end&&!day.qa).flatMap(day=>{const value=mode==="retention"?day.retention:day.value;return value===null?[]:[value];}));
 const low=values.length?Math.min(...values):0,high=values.length?Math.max(...values):100,padding=Math.max((high-low)*.08,Math.abs(high)*.03,.01);
 const min=low-padding,max=high+padding,width=1180,height=570,left=85,right=1110,top=85,bottom=470;
 const x=(time:number)=>left+time/Math.max(1,end)*(right-left),y=(value:number)=>bottom-(value-min)/(max-min)*(bottom-top),color=materialStyle(sample.material_family).color;
 const title=`Sensibilité en extérieur · ${sample.material_raw||sample.material_family} · ${sample.sample_uid}`;
 const unit=mode==="retention"?"Rétention (%)":metric==="pr"?"PR du capteur (%)":"Pmpp (W)";
 const caption=`Exposition extérieure, ${metric.toUpperCase()} ; cellule ${sample.sample_uid}, ${sample.material_raw}, lot ${sample.batch_no_raw??"inconnu"}. ${ribbonSelection!==ALL_RIBBONS?`Filtre : ${ribbonSelectionLabel(ribbonSelection)}. `:""}Médianes journalières recalculées à partir des mesures brutes pour une irradiance ≥100, ≥200 et ≥300 W/m² ; convention principale ≥200 W/m² / B7. ${mode==="retention"?`Chaque scénario est normalisé par ses ${window} premiers jours valides au maximum (minimum 3), puis multiplié par 100.`:"Valeurs journalières absolues."} Trajectoire individuelle, sans regroupement ; exclusions propres à la grandeur ; jusqu'au jour ${end}, sans interpolation. Les dates manquantes interrompent les courbes. Le tableau de sensibilité final utilise la dernière date valide propre à chaque scénario : il ne constitue pas une comparaison à temps commun. La définition du PR du capteur reste à confirmer.`;
 const analyticalRows=displayed.filter(row=>!hidden.includes(row.threshold)).flatMap(row=>row.daily.filter(day=>day.time<=end&&!day.qa&&(mode==="absolute"?day.value:day.retention)!==null).map(day=>({sample_uid:sample.sample_uid,threshold:row.threshold,baselineWindow:window,baseline:row.baseline,baselineDates:row.baselineDates,metric,mode,...day,plottedValue:mode==="absolute"?day.value:day.retention,sourceRows:allDaily.find(raw=>raw.threshold===row.threshold&&raw.date===day.date&&raw.source===day.source)?.retainedSourceRows})));
 const actualContributors=displayed.some(row=>row.daily.some(day=>!outdoorFigureExclusions(day,row.baseline,mode,end).length))?[sample.sample_uid]:[];
 const exclusions=displayed.flatMap(row=>row.daily.flatMap(day=>{
  const reasons=outdoorFigureExclusions(day,row.baseline,mode,end);
  return reasons.length?[{sampleUid:sample.sample_uid,threshold:row.threshold,date:day.date,reasons}]:[];
 }));
 const manifest={schemaVersion:"iv-compare-outdoor-figure/1",generatedAt:new Date().toISOString(),sourceCode:buildIdentity,dataset:{name:dataset.name,packageSha256:hash},provenance:bundle.provenance,figureType:"outdoor-sensitivity",title,caption,selectedSamples:[sample],ribbonSelection,actualContributors,scenarios,analyticalRows,policy:bundle.analysis.policy,
  exclusions,tableScope:"Full record: independent of graph end and visual hiding; last valid dates are scenario-specific",display:{preset:"TM publication",width,height,mode,metric,window,hiddenThresholds:hidden,graphEnd:end,viewport:{xMin:0,xMax:end,yMin:min,yMax:max}}};
 const graphic=async(format:"svg"|"png",preset:"default"|"report"="default")=>{if(!svg.current)return;try{await downloadScientificGraphic(svg.current,width,height,manifest,"outdoor-sensitivity",format,preset);setExportError(null);}catch(error){setExportError(String(error));}};
 return <section className="chart-card" aria-label="Sensibilité en extérieur">
  <h3>Sensibilité en extérieur <InfoTip text="Thresholds are recomputed from raw logger rows, not from the existing daily medians. B3/B7/B14 are the first up to 3/7/14 QA-valid daily medians; at least 3 days are required. No favorable threshold or baseline is selected automatically. Files lacking irradiance cannot support this comparison."/></h3>
  <div className="control-row"><label>Outdoor specimen <select value={sample.sample_uid} onChange={event=>{setSampleId(event.target.value);setGraphEnd(null);}}>{samples.map(row=><option key={row.sample_uid} value={row.sample_uid}>{row.sample_uid} · {row.material_raw} · {row.sample_id_raw}</option>)}</select></label><label>Outdoor metric <select value={metric} onChange={event=>setMetric(event.target.value as typeof metric)}><option value="pr">Logger PR</option><option value="pmpp">Pmpp</option></select></label><label>Sensitivity baseline <select value={window} onChange={event=>setWindow(Number(event.target.value) as typeof window)}><option value={3}>B3</option><option value={7}>B7 — primary</option><option value={14}>B14</option></select></label><label>Outdoor values <select value={mode} onChange={event=>setMode(event.target.value as typeof mode)}><option value="retention">Retention</option><option value="absolute">Absolute daily median</option></select></label><label>Outdoor graph end (days)<input type="number" min={0} value={end} onChange={event=>setGraphEnd(Math.max(0,Number(event.target.value)))}/></label><button onClick={()=>setGraphEnd(null)}>All days</button></div>
  <div className="control-row">{thresholds.map(threshold=><label key={threshold}><input type="checkbox" checked={!hidden.includes(threshold)} onChange={()=>setHidden(current=>current.includes(threshold)?current.filter(value=>value!==threshold):[...current,threshold])}/> Show ≥{threshold} W/m²</label>)}<InfoTip text="Hiding a scenario is display-only and does not change its statistics. Each threshold is a separate sensitivity calculation, never an independent replicate."/></div>
  <div className="control-row">{(["svg","png"] as const).map(format=><button key={format} onClick={()=>void graphic(format)}>Export {format.toUpperCase()}</button>)}<button onClick={()=>void graphic("svg","report")}>Report SVG</button><button onClick={()=>downloadFigureFile(rowsCsv(analyticalRows),"outdoor-sensitivity.figure.csv","text/csv")}>Data shown in figure CSV</button><button onClick={()=>downloadFigureFile(rowsCsv(allDaily.map(row=>({...row,qaByMetric:scenarios.filter(s=>s.threshold===row.threshold&&s.window===7).map(s=>({metric:s.metric,qa:s.daily.find(day=>day.date===row.date&&day.source===row.source)?.qa})),registrySha256:bundle.provenance.registrySha256,sourceSha256:bundle.provenance.rawFileHashes[row.source],packageSha256:hash,sourceCode:buildIdentity}))),"outdoor-sensitivity.full-selected.csv","text/csv")}>Full selected dataset CSV</button><button onClick={()=>downloadFigureFile(JSON.stringify(manifest,null,2),"outdoor-sensitivity.figure.json","application/json")}>Figure manifest JSON</button><button onClick={()=>void navigator.clipboard.writeText(caption).catch(()=>downloadFigureFile(caption,"outdoor-sensitivity.caption.txt","text/plain"))}>Copy caption</button></div>
  {exportError&&<p role="alert">{exportError}</p>}
  <div style={{overflowX:"auto"}}><svg ref={svg} width={width} height={height} viewBox={`0 0 ${width} ${height}`} role="img" aria-label={title} style={{background:"white",fontFamily:"Arial, sans-serif"}}><rect width={width} height={height} fill="white"/><text x={width/2} y={28} textAnchor="middle" fontSize={20}>{title}</text><text x={left} y={67} fontSize={14}>{unit}</text>
   {Array.from({length:6},(_,i)=>min+(max-min)*i/5).map(value=><g key={value}><line x1={left} x2={right} y1={y(value)} y2={y(value)} stroke="#ddd"/><text x={left-10} y={y(value)+4} textAnchor="end" fontSize={12}>{value.toFixed(1)}</text></g>)}
   {Array.from({length:6},(_,i)=>end*i/5).map((value,i)=><text key={i} x={x(value)} y={bottom+24} textAnchor="middle" fontSize={12}>{value.toFixed(0)}</text>)}<text x={right} y={bottom+45} textAnchor="end" fontSize={14}>Exposition (jours)</text>
   {displayed.filter(row=>!hidden.includes(row.threshold)).map(row=><g key={row.threshold}>{row.daily.map((day,i)=>{const previous=row.daily[i-1],value=mode==="absolute"?day.value:day.retention,previousValue=mode==="absolute"?previous?.value:previous?.retention;if(value===null||day.qa||day.time>end)return null;return <g key={`${day.source}:${day.date}`}>{previousValue!==null&&previousValue!==undefined&&!previous.qa&&day.time-previous.time<=1&&<line x1={x(previous.time)} x2={x(day.time)} y1={y(previousValue)} y2={y(value)} stroke={color} strokeWidth={row.threshold===200?2.4:1.4} strokeDasharray={dash[row.threshold]}/>}<circle cx={x(day.time)} cy={y(value)} r={row.threshold===200?3:2} stroke={color} fill={row.threshold===100?"white":color}><title>{row.threshold} W/m² · {day.date}: {number(value)} · {day.retainedRows} raw rows · absolute {number(day.value)} · B{window}={number(row.baseline)}</title></circle></g>;})}</g>)}
   {thresholds.filter(value=>!hidden.includes(value)).map((threshold,i)=><g key={threshold}><line x1={left+i*290} x2={left+35+i*290} y1={height-24} y2={height-24} stroke={color} strokeWidth={2} strokeDasharray={dash[threshold]}/><text x={left+42+i*290} y={height-20} fontSize={13}>≥{threshold} W/m² · B{window}</text></g>)}
  </svg></div>
  {!values.length&&<p role="status">No eligible values: inspect missing irradiance, QA and baseline availability below.</p>}
  <details open><summary>Full-record sensitivity — independent of graph end; last valid dates are scenario-specific</summary><table><thead><tr>{["Threshold (W/m²)","Window","Raw rows retained","Valid days","Baseline","Baseline dates","Last date","Last value","Final retention (%)","Δ primary (pp)"].map(label=><th key={label}>{label}</th>)}</tr></thead><tbody>{scenarios.map(row=><tr key={`${row.threshold}:${row.window}`}><td>{row.threshold}</td><td>B{row.window}</td><td>{row.retainedRows} / {row.rawCount}</td><td>{row.validDays}</td><td>{number(row.baseline)} (n={row.baselineDays})</td><td>{row.baselineDates[0]??"—"} → {row.baselineDates.at(-1)??"—"}</td><td>{row.lastDate??"—"}</td><td>{number(row.lastValue)}</td><td>{number(row.finalRetention)}</td><td>{number(row.differenceFromPrimaryPp)}</td></tr>)}</tbody></table></details>
  <details><summary>Daily values, exclusions and baseline references</summary><table><thead><tr><th>Threshold</th><th>Date</th><th>Days</th><th>Raw n</th><th>Observed median</th><th>Value used</th><th>Retention (%)</th><th>QA</th></tr></thead><tbody>{displayed.flatMap(row=>row.daily.map(day=><tr key={`${row.threshold}:${day.source}:${day.date}`}><td>{row.threshold}</td><td>{day.date}</td><td>{day.time}</td><td>{day.retainedRows}</td><td>{number(day.observedValue)}</td><td>{number(day.value)}</td><td>{number(day.retention)}</td><td>{day.qa??"eligible"}</td></tr>))}</tbody></table></details>
 </section>;
}
