import Link from "next/link";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Guide & scientific methods — IV Compare",
  description: "Use IV Compare and understand its references, grouping, QA, uncertainty and interpretation limits.",
};

const chapters = [
  ["workflow", "Getting started"], ["metrics", "Metrics & protocols"],
  ["references", "Retention & references"], ["groups", "Groups & cohorts"],
  ["statistics", "Statistics & sample counts"], ["quality", "Quality & missing data"],
  ["jv", "Reading JV curves"], ["paired", "Before / after encapsulation"],
  ["exports", "Figures, exports & provenance"],
] as const;

export default function Guide() {
  return <main className="app-shell guide-shell">
    <a className="skip-link" href="#guide-content">Skip to guide</a>
    <header className="topbar">
      <Link className="brand-mark" href="/" aria-label="IV Compare workspace">IV</Link>
      <div><p className="eyebrow">Internal tool · IV data</p><h1>IV Compare</h1></div>
      <nav className="site-nav" aria-label="Main navigation"><Link href="/">Workspace</Link><Link href="/guide" aria-current="page">Guide & methods</Link></nav>
      <Link className="soft-button guide-back" href="/">Open workspace →</Link>
    </header>
    <section className="guide-hero">
      <p className="eyebrow">A guide to informed comparisons</p>
      <h2>Know what you are<br /><span>looking at.</span></h2>
      <p>From your first graph to a traceable figure: understand the data, the defaults and the limits of each comparison.</p>
      <div className="guide-principles"><span>Same-sample references</span><span>Explicit scientific choices</span><span>Preserved raw observations</span></div>
    </section>
    <div className="guide-layout">
      <aside className="guide-toc"><p className="eyebrow">On this page</p><nav aria-label="Guide chapters">{chapters.map(([id, title], index) => <a href={`#${id}`} key={id}><span>{String(index + 1).padStart(2, "0")}</span>{title}</a>)}</nav><Link className="soft-button" href="/">Back to your comparison →</Link></aside>
      <article id="guide-content" className="guide-content">
        <section id="workflow"><p className="eyebrow">01 · Workflow</p><h3>Your first comparison</h3>
          <ol className="guide-steps">
            <li><strong>Choose the question.</strong><p><b>Ageing trends</b> follows a metric over recorded durations. <b>JV curves</b> inspects measured sweeps of one cell through ageing or materials at one exact time. <b>Before / after</b> compares paired inventory PCE around encapsulation.</p></li>
            <li><strong>Choose the data.</strong><p>Each series has its own encapsulant family, protocol and metric. Add a series to compare another material or another condition. Open <b>Refine selection</b> to restrict formulation, batch, recipe or recorded electrode. A family name is a navigation label, not proof of equivalence.</p></li>
            <li><strong>Read individual samples first.</strong><p>The default draws separate selected-sample trajectories. Material colour stays the same; line patterns distinguish cells. Open the sample selector below the graph to check which inventory references contribute. Switching to Median or Mean aggregates the selected subset.</p></li>
            <li><strong>Arrange your graphs.</strong><p><b>Graph layout</b> groups by metric by default: POE and TPO forward sweeps share one graph, and their reverse sweeps share another. Choose <b>By material</b> to compare Pearl sweep directions within each material, or <b>One graph per series</b> to keep comparison cards separate. Choose Auto, Stacked or Side by side for the grid. Each graph has its own scale; incompatible metrics or protocols remain separate. These choices do not change calculations or sample selection.</p></li>
            <li><strong>Check the method and coverage.</strong><p>The current-method strip records the active trend choices. Open <b>Scientific settings</b> for grouping, cohort, Outdoor reference or flagged-data review. Opening a panel does not change the calculation. Check missingness, exclusions and cohort composition before interpreting a change.</p></li>
            <li><strong>Reduce dense displays if needed.</strong><p>For time axes in hours, <b>Point spacing</b> offers all points or intervals of 1, 2, 5, 10 or 24 hours. Each curve keeps its first point, then the first actual measurement at least that interval after the previous displayed point, and always its last point. No averages or synthetic timestamps are created. Statistics, references, analytical tables and automatic Y limits still use the full eligible data. Sparse displays can conceal short events: return to All points to inspect them.</p></li>
            <li><strong>Export with context.</strong><p>Choose a figure export for the displayed time range and point spacing, or the full selected dataset for the complete selection. The figure CSV follows the displayed points; the manifest records the spacing rule. Keep the companion method information and identifiers when sharing a scientific result.</p></li>
          </ol>
          <div className="guide-note"><strong>Help where you need it</strong><p>The round “i” buttons explain controls. Hover, focus with Tab or tap to read them. Move onto the explanation to keep it open; Escape or a tap outside dismisses it.</p></div>
        </section>
        <section id="metrics"><p className="eyebrow">02 · Measurements</p><h3>Different metrics answer different questions</h3>
          <div className="table-scroll"><table><caption>Recorded quantities and their interpretation</caption><thead><tr><th>Metric</th><th>Meaning</th><th>Interpretation limit</th></tr></thead><tbody>
            <tr><td>PCE / efficiency (%)</td><td>Electrical maximum power divided by incident light power.</td><td>Inventory PCE and a reconstruction from JV points are separate sources. Calibration and measurement conditions still matter.</td></tr>
            <tr><td>Jsc (mA/cm²)</td><td>Current density at zero voltage.</td><td>Current-to-density conversion requires a documented area; a unit assumption cannot establish calibration.</td></tr>
            <tr><td>Voc (V)</td><td>Voltage at zero current.</td><td>A shift can suggest changed losses, but cannot identify a unique physical mechanism.</td></tr>
            <tr><td>FF (%)</td><td>100 × Pmax / (Voc × Jsc), with consistent density units.</td><td>Curve shape can reflect multiple resistive or recombination effects.</td></tr>
            <tr><td>Outdoor PR (%)</td><td>The Performance Ratio reported by the logger, aggregated daily.</td><td>The laboratory confirms standard PR normalization. An empirical check finds PR proportional to Pmpp/G with a numerical reference matching Unaged PCE; power units and the logger configuration still need confirmation.</td></tr>
            <tr><td>Outdoor Pmpp (W)</td><td>Measured maximum power outdoors.</td><td>Irradiance and temperature vary; a power change alone does not isolate ageing.</td></tr>
            <tr><td>Irradiance (W/m²)</td><td>Incident light measured by the logger.</td><td>Provides exposure context, not a cell-stability metric.</td></tr>
            <tr><td>Pearl Pout (mW/cm²)</td><td>Paired forward/reverse arithmetic mean, or either sweep direction separately.</td><td>The mean uses both readings from the same cell and source row, before normalization. Missing or negative readings cannot supply a pair. Nominal Light ageing is confirmed at 1 sun / 40 °C; no calibrated PCE is newly inferred.</td></tr>
          </tbody></table></div>
          <p><b>DH</b> means damp heat and uses hours; <b>TC</b> means thermal cycling and uses cycles; <b>Outdoor</b> uses days; <b>Light ageing</b> uses recorded elapsed hours. <b>Unaged</b> is the initial post-encapsulation observation. Equal numerical durations across different protocols are not equivalent stresses. The laboratory confirms nominal DH at 85 °C and 85% relative humidity, TC between −40 and 85 °C, and Light ageing at 1 sun and 40 °C. TC ramps and dwell times, exposure interruptions and per-run condition logs still need documentation.</p>
          <p>Series with incompatible units or absolute metrics use separate panels. A compatible scale allows a descriptive overlay; it does not remove differences in experimental conditions.</p>
        </section>
        <section id="references"><p className="eyebrow">03 · Normalization</p><h3>What does 100% retention mean?</h3>
          <div className="guide-formula">Retention (%) = 100 × same-sample value / reference</div>
          <p>A reference is calculated separately for each sample and metric. Normalization happens before grouping. A group’s retention is therefore a summary of individual ratios, not the ratio of two group summaries.</p>
          <div className="guide-grid">
            <div><h4>DH / TC</h4><p>The unique, eligible Unaged value of the same sample supplies the reference. Time zero is post-encapsulation, not a pre-encapsulation interpolation. A missing, ambiguous, zero or negative reference cannot support a ratio.</p></div>
            <div><h4>Outdoor · B7 by default</h4><p>The median of up to the first seven QA-valid daily values, with at least three required. B3 and B14 use up to three and fourteen valid days for sensitivity. These days need not be consecutive.</p></div>
            <div><h4>Pearl Light ageing</h4><p>The first remaining recorded point for that cell and selected metric is the reference, after documented different-irradiance exclusions. The combined metric is (Pout F + Pout R) / 2 at each recorded time; retention is 100 × this mean / its initial mean, rather than the average of two separate retentions. Both readings are required, and QA from either direction applies. An invalid initial pair does not shift the reference to a later time. Forward and reverse are also available separately. The owner-confirmed 1.5-sun test and its recovery transition (worksheet rows 5–6 and 84–87) are excluded from the standard 1-sun analysis, even with QA inspection enabled. The first point is not necessarily the physical beginning of exposure.</p></div>
            <div><h4>Read absolute values too</h4><p>PCE of 12% becoming 9% means 75% retention, a loss of 3 percentage points and a relative loss of 25%. A cell initially at 1% and one at 12% can both start at 100% retention.</p></div>
          </div>
          <p>References below 0.5% PCE are flagged for inspection, not adjusted. A small denominator can amplify relative variation. Retention above 100% means a value above the selected reference, not proof of improved intrinsic stability.</p>
          <h4>Why the Outdoor irradiance threshold?</h4><p>Daily PR, Pmpp and irradiance are medians over logger observations at irradiance ≥200 W/m². This limits low-light and night-time instability. Electrical-only sources retain median positive Pmpp with a QA flag; without irradiance they cannot support threshold sensitivity.</p>
          <div className="guide-note"><strong>What the Outdoor data reveal about PR</strong><p>On 93,425 held-out measurements from 21 source files (G ≥200 W/m²), the relation PR_pct ≈ 100000 × raw_Pmpp / (G × Unaged_PCE_pct) reproduces the logger values with mean absolute error of about 0.0031 percentage points, without fitting a reference. This is an empirical inference. With the confirmed active area of 1 cm², the relation is consistent with Pmpp in mW. The package currently labels Pmpp as W; the raw CSV header provides no unit, so that unit must be verified before correction. The logger PR already has a reference; the site’s PR retention relative to B7 is a separate normalization.</p><p>Temperature-corrected PR cannot be independently checked without cell temperature and a thermal coefficient. The daily median used by this site differs from an energy-yield PR calculated over a full day. <a href="https://pvpmc.sandia.gov/modeling-guide/5-ac-system-output/pv-performance-metrics/performance-ratio/" target="_blank" rel="noreferrer">Standard PR definition (Sandia PVPMC)</a>.</p></div>
          <p>The Outdoor sensitivity view recalculates 100/200/300 W/m² thresholds and B3/B7/B14 references. The main convention remains 200 W/m² and B7. The full-record sensitivity table ignores graph end and visual hiding: last dates can differ between scenarios, so final differences are not a common-time comparison.</p>
        </section>
        <section id="groups"><p className="eyebrow">04 · Analytical membership</p><h3>A material family is not a controlled experiment</h3>
          <p>Conservative grouping preserves formulation, batch, recipe and recorded electrode differences. Incompletely documented samples stay separate. A recipe describes a process; it is not a causal explanatory variable by itself. All recorded labels, including Ag/Cu, are confirmed by the laboratory. Confirmed names do not establish equivalence between formulations or processes.</p>
          <p>Other grouping modes intentionally pool differences. Grouping by batch, for example, can combine formulations or recipes within that batch and material family. These summaries describe the selected observations; they do not isolate a material effect.</p>
          <div className="guide-grid"><div><h4>Available observations</h4><p>All eligible selected cells contribute at each recorded duration. Sample counts can change. If low-performing cells stop being measured, an aggregate can rise even when no remaining cell recovers.</p></div><div><h4>Constant cohort</h4><p>Only cells present at every recorded time within the chosen start/end window contribute. This stabilizes membership but may favour surviving or more completely followed cells. It is a diagnostic, not an automatic correction for attrition.</p></div></div>
          <p>Use the cohort-composition table to inspect n, batches, entering and departing identifiers. Missing measurements are not replaced by zero. Duplicate sample/time rows are ambiguous, not additional replicates.</p>
          <h4>Ribbon classification is a dataset convention</h4><p>The named references 3M-3007, 3M-3011 and 3M-3012 stay distinct. Empty entries, “stand”, “too short”, “facing down” and “all the length” are classified as standard ribbon. The latter terms are preparation notes, not evidence of identical placement. Original labels remain in metadata and exports; new unknown labels stay separate.</p>
          <p>The ribbon filter applies to all views. Splitting by ribbon affects aggregates and boxes; individual trajectories and JV curves remain per sample. The paired view also offers descriptive pooling within a material family and grouping of some missing process metadata: both are explicit options, not evidence of equivalence.</p>
        </section>
        <section id="statistics"><p className="eyebrow">05 · Uncertainty</p><h3>Spread and precision are different</h3>
          <div className="guide-grid"><div><h4>Median + IQR</h4><p>The median describes the centre. Q1–Q3 covers the middle 50% of observations and describes their spread. Quantiles use linear interpolation at (n−1) × p, also called type 7. With one cell there is no interval; with two cells median mode shows the observations without an IQR.</p></div><div><h4>Mean + 95% CI</h4><p>The arithmetic mean uses sample standard error and a two-sided t multiplier through n=30; above that, 1.96 is used. This precision diagnostic depends on independence assumptions which the dataset alone cannot establish.</p></div></div>
          <div className="guide-note"><strong>A very wide interval is not a measured extreme</strong><p>Two values of 60 and 120 have mean 90 and a 95% interval of about −291 to 471 because the n=2 t multiplier is 12.706. No cell measured 471%. The interval is not silently truncated and is not a QA flag.</p></div>
          <p><b>n</b> counts contributing sample identifiers at that time; <b>b</b> counts recorded batches. Raw points, repeated sweeps, observations, selected cells and independent experimental replicates are different counts. The laboratory confirms one sample UID represents one cell. Shared substrates and statistical independence of cells or batches remain unspecified.</p>
          <p>There is no “best value” aggregation: selecting a different best cell at each duration would create an artificial trajectory. Statistical outliers are not removed merely to improve a graph’s appearance.</p>
        </section>
        <section id="quality"><p className="eyebrow">06 · QA</p><h3>Flagged, missing and measured zero are different</h3>
          <p>QA means quality assurance. By default, documented source flags and reproducible review screens exclude affected observations from applicable trend calculations and references. <b>Include QA-flagged data</b> restores flagged observations for explicit review; it cannot invent missing values, resolve ambiguous identities or make a zero reference usable. The raw sources remain unchanged.</p>
          <details><summary>Laboratory trend review rules</summary><p>PCE outside 0–50%, Jsc outside 0–100 mA/cm², Voc outside 0–5 V and FF outside 0–100% are flagged. An isolated value at most 10% of both neighbouring values is also flagged if those neighbours agree within a ratio of 1.35, for the same sample, protocol and unit. Sustained and terminal zero values remain. These are project review thresholds, not universal physical bounds or a diagnosis.</p></details>
          <details><summary>Outdoor review rules</summary><p>PR outside 0–150%, irradiance outside 0–1,600 W/m² and negative Pmpp are flagged. With at least six neighbouring values among the nearest fourteen, isolated high-side spikes exceed the local median plus the larger of six robust standard deviations (MAD × 1.4826) and 1.5 times that median. A very low isolated value can also be flagged when nearby positive observations on both sides recover and agree.</p><p>Day zero PR or Pmpp is provisionally excluded when days one and two are positive, agree within a ratio less than 1.35, and day zero is below 25% of their smaller value. This screen does not identify an instrument fault. Documented owner adjudications apply to exact source/sample/date combinations and the affected metric; PR exclusions do not automatically exclude Pmpp.</p></details>
          <p>The missingness table distinguishes observed values, QA exclusions and unavailable measurements. The laboratory reports that follow-up stops because of cell failure. The current data do not encode an individual failure date for every absence: a blank remains missing, not a measured zero or an automatically assigned failure time. Open point details to inspect the absolute numerator, reference value and source rows.</p>
          <div className="guide-note"><strong>An empty graph is informative</strong><p>Check protocol and metric availability, restrictive filters, selected cells, a positive unique reference and the QA disclosure. In JV mode check exact shared times or a sample with at least two measured stages. Loosening a filter changes the question; record that choice.</p></div>
        </section>
        <section id="jv"><p className="eyebrow">07 · Curve inspection</p><h3>Inspect a sweep without overstating its validation</h3>
          <p><b>One cell over ageing</b> offers samples with raw curves at two or more exact stages. Earliest and latest stages are selected initially; at least two remain selected. All overlaid curves belong to the same UID. <b>Materials at one time</b> uses only the chosen exact duration: no nearest-time substitution or synthetic interpolation between stages.</p>
          <div className="guide-note"><strong>Light soaking and the laboratory plateau choice</strong><p>The laboratory performs successive JV measurements under illumination as performance rises towards a plateau, and retains the plateau value. This is an experimental selection rule, separate from the website’s representative-sweep rule. The plateau is recognized when efficiency stops increasing, according to the laboratory. No numerical tolerance, minimum duration or number of scans was supplied, and the exact retained sweep is not encoded for each observation. Performance variations and the resulting methodological limitation will be discussed in the report. A plateau selected from JV scans should not be described as independently verified steady-state MPP tracking.</p></div>
          <p>The laboratory identifies its equipment as the <a href="https://www.adtec.com/english/products/detail.html?pdid=10420" target="_blank" rel="noreferrer">ADTEC Super Solar Simulator</a>. The manufacturer describes continuous simulated light from xenon and halogen sources. The product page identifies the equipment family; it does not establish the settings or calibration used for these measurements.</p>
          <p>A representative selection is made specimen first, then sweep, near median eligible efficiency. Repeated acquisitions do not create independent specimens. You can select an exact measurement; maximum efficiency is never chosen automatically. Missing PCE follows a deterministic identifier fallback rather than a “best” rule.</p>
          <div className="guide-grid"><div><h4>Sign & segments</h4><p>Instrument convention shows negative photocurrent; PV convention reverses only its sign. Voltage jumps and reversals split the acquired sequence into segments. Primary-segment display and All data scale affect inspection; the point audit discloses the displayed/archived counts.</p></div><div><h4>Screening ≠ validation</h4><p>A usable branch and numerical consistency permit default inspection. Quantitative eligibility separately requires numerical consistency, unit validation, acquired-range evidence, experimental validation, full photovoltaic coverage and no source QA flag. Legacy conversion text is not that evidence.</p></div></div>
          <p>Unvalidated legacy curves remain inspection data. Enabling curves failing screening broadens source review, not scientific validation. Inventory PCE comparisons remain available independently of raw JV eligibility.</p>
          <h4>How reconstructed metrics are obtained</h4><p>Reconstruction uses piecewise-linear measured J(V), a bracketed zero for Voc and the analytic maximum of V×J within each interval. It does not extrapolate, rescale to instrument summaries or replace instrument values. Reconstructed PCE requires explicit positive incident power; if unavailable, PCE stays unavailable. Chart landmarks are reading aids; the chart MPP marker uses the measured point of greatest delivered power.</p>
          <details><summary>Numerical discrepancy and repeated-segment screens</summary><p>A severe discrepancy exceeds the larger of an absolute floor and a fraction of the instrument value: Jsc 25% / 0.5 mA/cm²; Voc 10% / 0.05 V; Pmpp 25% / 0.5 mW/cm²; FF 20% / 5 percentage points; PCE 25% / 1 percentage point. These screens do not estimate uncertainty or establish calibration.</p><p>Repeated-segment detection requires at least ten aligned points and three distinct files, equal point counts, voltage differences ≤10⁻⁶ V and normalized-current differences ≤5×10⁻⁵. Exact, near and multiplicatively scaled sequences are distinguished. A suspect segment requires adjudication: similarity alone does not prove an export residue, and absence of a flag does not prove acquisition.</p></details>
        </section>
        <section id="paired"><p className="eyebrow">08 · Paired comparisons</p><h3>Before / after uses the same cell</h3>
          <p>Before is <b>Initial Eff</b> in the inventory; after is the same UID’s unique eligible <b>Unaged</b> PCE. Selected material families and ribbon choices define coverage independently of trend sample filters and ageing settings. Missing, negative, non-finite or ambiguous pairs are excluded. A measured zero after remains included.</p>
          <p>Boxes show Q1, median and Q3. Whiskers end at the most extreme observations within 1.5 IQR; every point, including outliers, remains visible. Groups with fewer than three pairs show points only. Connecting paired cells is optional and off by default.</p>
          <div className="guide-formula">Absolute change (pp) = after − before<br />Relative change (%) = 100 × (after − before) / before</div>
          <p>From 12% to 9% PCE: −3 percentage points or −25% relative change. A zero before supports an absolute difference but no relative difference. Mean or median of individual changes differs from the relative change of group means; alternative summaries are disclosed separately.</p>
          <p>The Before/Post/Aged diagnostic uses one exact DH/TC stage. Last common time requires a valid observation for every non-excluded selected sample; it does not substitute each cell’s last measurement. Stage counts can differ. Ageing retention is aged/post, not post/before. Synchronized PCE/Jsc/Voc/FF panels use the same sample/time grid and leave unavailable metrics explicit.</p>
          <p>Dates appear only when source links support them. The laboratory confirms storage in the dark in a small box under nitrogen. The before/after interval varies and can be displayed when linked dates are available. Variable storage duration and light-soaking measurement history still prevent interpreting a paired change as an isolated causal effect of encapsulation. Descriptive family pooling may combine formulations, batches and processes; original group provenance remains in exports.</p>
        </section>
        <section id="exports"><p className="eyebrow">09 · Reproducibility</p><h3>Keep the figure and its analytical context together</h3>
          <p><b>Graph end</b> restricts the displayed time range and figure rows. It does not interpolate a new observation at the cutoff. <b>Full selected dataset CSV</b> retains the complete selected series beyond that cutoff, with analytical traces. Check which export you need before comparing row counts.</p>
          <p>Auto Y includes displayed observations and visible intervals with padding. Manual Y bounds, zoom and hiding intervals change presentation; they do not alter recorded calculations. Hidden intervals are omitted from visual scaling only. Clipping is disclosed. Hiding a trend legend entry changes display rather than analytical membership; explicit exclusion and sample filtering change membership. Paired exports instead follow the visible paired groups.</p>
          <p>PNG/SVG figures use one material legend entry for individual trajectories; aggregate legends show contributing N or its minimum–maximum range. Exact counts and provenance remain in companion data and manifests. Report SVG changes typography, axes and colours only.</p>
          <p>Source files are archived under data/raw, derived audit inputs under data/processed, and browser packages under public/data. The package embeds SHA-256 source provenance. Source rows, matching reasons, normalization and QA flags support traceability; a hash proves identity of content, not correctness of its scientific interpretation.</p>
          <p>Imports are processed locally in the browser and replace the loaded dataset. Limits are 64 MB for .ivpack, 32 MB for workbooks and 256 MB for point TSVs. Schema, uniqueness, relationships, finite values, curve length and counts are checked. A compatible source package is required for the supplemental Outdoor sensitivity artifact.</p>
          <p>Provisional filename/inventory links remain provisional. Ambiguous or unlinked files need identity review. Reference cells and laboratory Trash sources are preserved for audit but excluded from polymer-matching failures. FTIR, SEM and cell photos are archived context, not inferred measurements in these graphs. Extended Outdoor sources supersede their historical records without double counting.</p>
          <div className="guide-note"><strong>Before sharing a result</strong><p>Record metric and units, protocol and exact time range, filters and grouping, reference definition, QA inclusion, cohort counts, uncertainty type, source package and any visual clipping. Keep the figure data and manifest alongside the graphic.</p></div>
        </section>
        <Link className="primary-button" href="/">Return to the workspace →</Link>
      </article>
    </div>
    <footer><span>IV Compare · Methods explained from the repository’s calculation rules</span><a href="#workflow">Back to the start ↑</a></footer>
  </main>;
}
